package tables;
import java.sql.Timestamp;  

import javax.persistence.Column;
import javax.persistence.Entity;  
import javax.persistence.Id;  
import javax.persistence.Table;  
import javax.persistence.Version;  
  
/** 
 * A simple entity bean. This table does not have to exist if 
 * you use Ebean's DDL generation. 
 */  
@Entity  
@Table(name="ml_authors")  
public class MLAuthor {  
      
    @Id  
    Integer RowId; //database autogenerated primary key
    
    Integer Rank; //rank within the Machine Learning field
    
    Integer ID; //Author ID from the data, not to confuse with the row id!
    Integer PublicationCount;
    Integer CitationCount;
    String FirstName;
    String MiddleName;
    String LastName;
    String NativeName;
    
    @Column(columnDefinition = "TEXT")
    String HomepageURL;
    
    //Organization fields
    Integer OrgID;
    String OrgName;
    
    String DisplayPhotoURL;
    Integer HIndex;
    Integer GIndex;
    
    //Research Interest Domain fields
    String Dom1;
    String Dom2;
    String Dom3;
      
    @Version  
    Timestamp lastUpdate;  
      
    public Integer getRowId() {  
        return RowId;  
    }  
  
    public void setRowId(Integer RowId) {  
        this.RowId = RowId;  
    }  
  
    public Integer getRank() {  
        return Rank;  
    }  
  
    public void setRank(Integer Rank) {  
        this.Rank = Rank;  
    } 
    
    public Integer getID() {  
        return ID;  
    }  
  
    public void setID(Integer ID) {  
        this.ID = ID;  
    } 
    
    public Integer getPublicationCount() {  
        return PublicationCount;  
    }  
  
    public void setPublicationCount(Integer PublicationCount) {  
        this.PublicationCount = PublicationCount;  
    } 
    
    
    public Integer getCitationCount() {  
        return CitationCount;  
    }  
  
    public void setCitationCount(Integer CitationCount) {  
        this.CitationCount = CitationCount;  
    }  
    
    public String getFirstName() {  
        return FirstName;  
    }  
  
    public void setFirstName(String FirstName) {  
        this.FirstName = FirstName;  
    }  
    
    public String getMiddleName() {  
        return MiddleName;  
    }  
  
    public void setMiddleName(String MiddleName) {  
        this.MiddleName = MiddleName;  
    }  
    
    public String getLastName() {  
        return LastName;  
    }  
  
    public void setLastName(String LastName) {  
        this.LastName = LastName;  
    }  
    
    public String getNativeName() {  
        return NativeName;  
    }  
  
    public void setNativeName(String NativeName) {  
        this.NativeName = NativeName;  
    }  
    
    public String getHomepageURL() {  
        return HomepageURL;  
    }  
  
    public void setHomepageURL(String HomepageURL) {  
        this.HomepageURL = HomepageURL;  
    }  
    
    public Integer getOrgID() {  
        return OrgID;  
    }  
  
    public void setOrgID(Integer OrgID) {  
        this.OrgID = OrgID;  
    }  
  
    public String getOrgName() {  
        return OrgName;  
    }  
  
    public void setOrgName(String OrgName) {  
        this.OrgName = OrgName;  
    }  
    
    public String getDisplayPhotoURL() {  
        return DisplayPhotoURL;  
    }  
  
    public void setDisplayPhotoURL(String DisplayPhotoURL) {  
        this.DisplayPhotoURL = DisplayPhotoURL;  
    }  
    
    public Integer getHIndex() {  
        return HIndex;  
    }  
  
    public void setHIndex(Integer HIndex) {  
        this.HIndex = HIndex;  
    }
    
    public Integer getGIndex() {  
        return GIndex;  
    }  
  
    public void setGIndex(Integer GIndex) {  
        this.GIndex = GIndex;  
    }
    
    public String getDom1() {  
        return Dom1;  
    }  
  
    public void setDom1(String Dom1) {  
        this.Dom1 = Dom1;  
    }  
    
    public String getDom2() {  
        return Dom2;  
    }  
  
    public void setDom2(String Dom2) {  
        this.Dom2 = Dom2;  
    } 
    
    public String getDom3() {  
        return Dom3;  
    }  
  
    public void setDom3(String Dom3) {  
        this.Dom3 = Dom3;  
    } 
    
    public Timestamp getLastUpdate() {  
        return lastUpdate;  
    }  
  
    public void setLastUpdate(Timestamp lastUpdate) {  
        this.lastUpdate = lastUpdate;  
    }  
  
}  